name: herramientas
channels:
- conda-forge
- r
- anaconda
- bioconda
- nodefaults
- pkgw
dependencies:
- jupyterlab
- ipywidgets
- nodejs
- texlive-core
- texlive-selected
- r-essentials
- gnuplot
- sympy
- numpy
- matplotlib
- requests
- beautifulsoup4
- zip
- pip:
  - git+https://github.com/has2k1/gnuplot_kernel.git@master
